<?php

/**
 * @file
 * Contains events.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function events_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the events module.
    case 'help.page.events':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My events module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function events_theme() {
  return [
    'events' => [
      'render element' => 'children',
    ],
  ];
}
